local _, addon = ...
local locales = {
    enUS = {
        Buy = "Buy %d items (one full stack)",
        Price = "Total: %s",
        Loading = "Waiting for item or bag information.",
        Bundle = "The merchant's bundles cannot make exactly one full stack.",
        Stock = "The merchant does not have a full stack in stock.",
        Money = "You do not have enough money for a full stack.",
        Bags = "There is not enough room in your bags for a full stack.",
        Unique = "Unique item limit: use the standard purchase button.",
        Unavailable = "This purchase is currently unavailable.",
    },
    frFR = {
        Buy = "Acheter %d objets (une pile complète)",
        Price = "Total : %s",
        Loading = "En attente des informations sur l’objet ou les sacs.",
        Bundle = "Les lots du marchand ne permettent pas d’acheter exactement une pile complète.",
        Stock = "Le marchand n’a pas une pile complète en stock.",
        Money = "Vous n’avez pas assez d’argent pour une pile complète.",
        Bags = "Vos sacs n’ont pas assez de place pour une pile complète.",
        Unique = "Limite d’objet unique : utilisez le bouton d’achat habituel.",
        Unavailable = "Cet achat est actuellement indisponible.",
    },
    deDE = {
        Buy = "%d Gegenstände kaufen (einen vollen Stapel)",
        Price = "Gesamt: %s",
        Loading = "Gegenstands- oder Tascheninformationen werden geladen.",
        Bundle = "Die Verkaufsmengen ergeben keinen vollständigen Stapel.",
        Stock = "Der Händler hat keinen vollständigen Stapel auf Lager.",
        Money = "Ihr habt nicht genug Geld für einen vollständigen Stapel.",
        Bags = "In Euren Taschen ist nicht genug Platz für einen vollständigen Stapel.",
        Unique = "Begrenzung für einzigartige Gegenstände: Verwendet die normale Kauftaste.",
        Unavailable = "Dieser Kauf ist derzeit nicht möglich.",
    },
    esES = {
        Buy = "Comprar %d objetos (una pila completa)",
        Price = "Total: %s",
        Loading = "Esperando los datos del objeto o de las bolsas.",
        Bundle = "Los lotes del vendedor no permiten comprar exactamente una pila completa.",
        Stock = "El vendedor no tiene una pila completa disponible.",
        Money = "No tienes suficiente dinero para una pila completa.",
        Bags = "No hay suficiente espacio en tus bolsas para una pila completa.",
        Unique = "Límite de objeto único: utiliza el botón de compra normal.",
        Unavailable = "Esta compra no está disponible en este momento.",
    },
    esMX = {
        Buy = "Comprar %d objetos (una pila completa)",
        Price = "Total: %s",
        Loading = "Esperando la información del objeto o de las bolsas.",
        Bundle = "Los paquetes del vendedor no permiten comprar exactamente una pila completa.",
        Stock = "El vendedor no tiene una pila completa disponible.",
        Money = "No tienes suficiente dinero para una pila completa.",
        Bags = "No hay suficiente espacio en tus bolsas para una pila completa.",
        Unique = "Límite de objeto único: usa el botón de compra normal.",
        Unavailable = "Esta compra no está disponible en este momento.",
    },
    itIT = {
        Buy = "Acquista %d oggetti (una pila completa)",
        Price = "Totale: %s",
        Loading = "In attesa dei dati dell’oggetto o delle borse.",
        Bundle = "I lotti del mercante non permettono di acquistare esattamente una pila completa.",
        Stock = "Il mercante non ha una pila completa disponibile.",
        Money = "Non hai abbastanza denaro per una pila completa.",
        Bags = "Non c’è abbastanza spazio nelle borse per una pila completa.",
        Unique = "Limite degli oggetti unici: usa il normale pulsante di acquisto.",
        Unavailable = "Questo acquisto non è attualmente disponibile.",
    },
    ptBR = {
        Buy = "Comprar %d itens (uma pilha completa)",
        Price = "Total: %s",
        Loading = "Aguardando informações do item ou das bolsas.",
        Bundle = "Os lotes do comerciante não permitem comprar exatamente uma pilha completa.",
        Stock = "O comerciante não tem uma pilha completa em estoque.",
        Money = "Você não tem dinheiro suficiente para uma pilha completa.",
        Bags = "Não há espaço suficiente nas suas bolsas para uma pilha completa.",
        Unique = "Limite de item único: use o botão de compra normal.",
        Unavailable = "Esta compra não está disponível no momento.",
    },
    ruRU = {
        Buy = "Купить %d шт. (полную стопку)",
        Price = "Итого: %s",
        Loading = "Ожидание данных о предмете или сумках.",
        Bundle = "Из партий торговца нельзя составить ровно одну полную стопку.",
        Stock = "У торговца нет полной стопки в наличии.",
        Money = "У вас недостаточно денег для покупки полной стопки.",
        Bags = "В сумках недостаточно места для полной стопки.",
        Unique = "Ограничение уникального предмета: используйте обычную кнопку покупки.",
        Unavailable = "Эта покупка сейчас недоступна.",
    },
    koKR = {
        Buy = "%d개 구매 (최대 묶음)",
        Price = "총 가격: %s",
        Loading = "아이템 또는 가방 정보를 기다리는 중입니다.",
        Bundle = "상인의 판매 단위로는 최대 묶음 수량을 정확히 구매할 수 없습니다.",
        Stock = "상인의 재고가 최대 묶음 수량보다 적습니다.",
        Money = "최대 묶음을 구매할 돈이 부족합니다.",
        Bags = "가방에 최대 묶음을 넣을 공간이 부족합니다.",
        Unique = "고유 아이템 제한: 기본 구매 버튼을 사용하세요.",
        Unavailable = "지금은 이 아이템을 구매할 수 없습니다.",
    },
    zhCN = {
        Buy = "购买%d件物品（一整组）",
        Price = "总价：%s",
        Loading = "正在等待物品或背包信息。",
        Bundle = "商人的出售数量无法恰好组成一整组。",
        Stock = "商人的库存不足一整组。",
        Money = "你的金钱不足以购买一整组。",
        Bags = "你的背包空间不足以容纳一整组。",
        Unique = "唯一物品数量限制：请使用默认购买按钮。",
        Unavailable = "目前无法购买此物品。",
    },
    zhTW = {
        Buy = "購買%d件物品（一整組）",
        Price = "總價：%s",
        Loading = "正在等候物品或背包資訊。",
        Bundle = "商人的販售數量無法恰好組成一整組。",
        Stock = "商人的庫存不足一整組。",
        Money = "你的金錢不足以購買一整組。",
        Bags = "你的背包空間不足以容納一整組。",
        Unique = "唯一物品數量限制：請使用預設購買按鈕。",
        Unavailable = "目前無法購買此物品。",
    },
}
locales.enGB = locales.enUS
local selected = locales[GetLocale()] or locales.enUS
addon.L = selected == locales.enUS and selected or setmetatable(selected, { __index = locales.enUS })
